version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_nestjs
    restart: always
    ports:
      - "5432:5432"
    environment:
     
      POSTGRES_DATABASE: coop
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  postgres_data:
