version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '3000:3000'
    environment:
     JWT_SECRET: 'randomsecret'
    volumes:
      - ./prisma:/app/prisma # Persistir o arquivo SQLite localmente
      - ./logs:/app/logs     # Opcional: salvar logs
